import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import PageWrapper from "@/layout/wrapper";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: React.FC<Readonly<{ children: React.ReactNode }>> = ({ children }) => {
  return (
    <html lang="en" className="h-full" suppressHydrationWarning>
      <body className="bg-slate-950 text-slate-200">
        <PageWrapper>
          {children}
        </PageWrapper>
      </body>
    </html>
  );
};

export default RootLayout;